NTUEELightDance/LightDance-Editor

README.md

Add Jira Software connection with Github.
Feature
None
https://ntueelightdance.atlassian.net/browse/EDITOR-1
Create branch starting with EDITOR-*Jira number*, and one can find out Github link in Jira's corresponding issue.

EDITOR-1. Build connection between Jira and Github repo.

---

.github/pull_request_template.md

In the pull request template, it requires the user to link to the JIRA issue. However, we don't use JIRA in this project.
Bug Fix
None.
https://github.com/NTUEELightDance/LightDance-Editor/issues/9
Add a new pull request after this PR merged.
None

EDITOR-#9. Fix the pull_request template. We don't use Jira in this project.

---

data/load.json
src/client/components/commandCenter/agent.js
src/client/components/file/index.js
src/client/components/file/utils.js
src/client/components/simulator/controller.js
src/client/components/wavesurfer/waveSurferApp.js
src/client/slices/globalSlice.js
src/client/slices/loadSlice.js
utils/transformControl.js

to support new format
Improvement
None
https://github.com/NTUEELightDance/LightDance-Editor/issues/16
npm start
* Are there breaking changes for older versions? idk

EDITOR-#16 Add new controlRecord format support

---

editor/components/simulator/controller.tsx
editor/components/simulator/index.tsx
editor/components/wavesurfer/waveSurferApp.tsx
editor/slices/globalSlice.tsx
editor/utils/math.tsx

This pull request is aim to fix the performance issue of simulator. 
1. Greatly reduce the delay caused by passing time & status through redux dispatch.
2. Only trigger play/pause by redux status "isPlaying"
3. Update frame and time when playPause button is pressed
4. Use pixi ticker to update the dancer status and position about time
Bug Fix
None
#6 
Just press the play button.
https://user-images.githubusercontent.com/55420821/145663197-a1c045c7-ee6d-4819-af1b-ee8821cb4919.mp4

EDITOR-#6 Optimize playing performance. 

---

editor/components/EffectList/index.tsx
editor/slices/globalSlice.ts

Complete all the operations for effect lists, including addEffect, deleteEffect, applyEffect.
[Features]
None
https://github.com/NTUEELightDance/LightDance-Editor/issues/60
None
None

EDITOR-#60. Operations for effect lists

---

editor-server/src/index.ts

Fix ondisconnect bug (frame's "editing" won't be deleted)
Bug Fix
None
#65 
1. request(Control/Position)Editing
2. close playground
3. reopen playground and checkout "editing" of frame which should be null
None

EDITOR-#65. fix disconnect bug

---

README.md
utils/initDB.js

Fix initDB and modify REAMDE.
Bug Fix
Fix #77 
```
cd utils
yarn
node initDB.js
```
None.

EDITOR-#77 InitDB doesn't run correctly. 

---

editor/components/Wavesurfer/MarkersPlugin/index.ts
editor/components/Wavesurfer/WaveSurferApp.ts
editor/components/Wavesurfer/index.tsx

[#79](https://github.com/NTUEELightDance/LightDance-Editor/issues/79)

EDITOR-#79 fix wavesurfer switch, add hover and change element size

---

editor/api/index.ts
editor/core/actions/edit.ts
editor/graphql/mutations.ts

Connect some mutation api, including add, save and delete control/position frame.
Feature
https://github.com/NTUEELightDance/LightDance-Editor/issues/58
For testing mutation api correctness, try to add, save or delete control/position frame and refresh. 
For testing update frontend cache correctness, use Apollo client dev tool to see cache. 

EDITOR-#58 link editor to editor-server with graphql

---

README.md
utils/oldInitDB.js

modify export.json to correct one
bug fix
[EDITOR-#96. Backend: exportData not the origin data](https://github.com/NTUEELightDance/LightDance-Editor/issues/96)
checkout export.json

EDITOR-#96. Correct export.json

---

editor/components/DancerList/index.tsx
editor/constants/index.ts
editor/graphql/queries.ts
editor/hooks/useDancer.ts

We want to get dancer data from the backend.
Feature
None
Resolve #93 
None
None

EDITOR-#93 Connect Dancer Graphql API

---

editor-server/src/models/Color.ts
editor-server/src/resolvers/color.ts
editor-server/src/resolvers/inputs/color.ts
editor-server/src/resolvers/types/color.ts
editor-server/src/schema.gql

Since color apis lack EDIT and DELETE functions, add editColor, addColor, deleteColor, getColors apis
Improvement
#107 
use graphql playground
colorMap api can still work just fine

EDITOR-#107 add color apis

---

editor/app.tsx
editor/components/ColorPalette/NewColorDialog.tsx
editor/components/ColorPalette/index.tsx
editor/containers/Layout/index.tsx
editor/core/actions/colorMap.ts
editor/core/actions/index.ts
editor/core/models/index.d.ts
editor/core/state/index.ts
editor/graphql/mutations.ts
editor/graphql/queries.ts
editor/hooks/useColorMap.ts
editor/layouts/beta.json
editor/package.json
editor/yarn.lock

We added color palette for editors to customized colors of fiber
Feature 
https://github.com/NTUEELightDance/LightDance-Editor/issues/112
yarn dev

EDITOR-#112 Add Color Palette

---

editor-server/src/index.ts
editor-server/src/models/User.ts
editor/client/index.ts

modify frontend wslink setting so that "editing" will be deleted when ondisconnecting.
Feature
[EDITOR-#104. Frontend subscription setting](https://github.com/NTUEELightDance/LightDance-Editor/issues/104)
1. open web
2. close/refresh web
3. the userID will be logged in terminal
Some bugs: When open the web, the user will be duplicated. (Refresh web is fine) 

EDITOR-#104 frontend subscription client setting

---

editor/components/Wavesurfer/MarkersPlugin/index.ts
editor/components/Wavesurfer/index.tsx
editor/hooks/useEditHandler.tsx

We want to see position's markers on waveSurferApp when switching editor to `POSITION_EDITOR`.
Fix clicking marker not setting time bug.
Fix adding but not change frame index bug.
Bug Fix && Improvement
None
Resolve #117 
Switch to the position editor and see the marker changes.
None

EDITOR-#117. Add Position Markers on WaveSurfer.

---

editor/client/index.ts
editor/client/subscription.ts
editor/core/actions/edit.ts
editor/graphql/index.ts
editor/graphql/mutations.ts
editor/graphql/subscriptions.ts

1. Connect subscription api to modify frontend data when co-working with others.
2. add "await" when calling add, save and delete functions in agent. 
3. fix typo in /graphql/mutation
Bug Fix, Feature
https://github.com/NTUEELightDance/LightDance-Editor/issues/97
Use different browser to use editor, and see if data change simultaneously. 
"await" added.

EDITOR-#97 Connect Subscription APIs for co-work & fix some bugs and typo in editor

---

editor-server/package.json
editor-server/src/models/Color.ts
editor-server/src/schema.gql
editor-server/src/utility.ts
editor-server/yarn.lock

Change custom id to  nanoid ( 10 digits )
Improvement 
Resolve #110 
query and see the ids

EDITOR-#110 Change id generation system to nanoid 

---

editor/components/EditButtons/index.tsx
editor/hooks/useEditHandler.tsx

Hotkey save should prevent default.
Besides, add reset time on delete.
Bug Fix
Resolve #125 
`ctrl+s, cmd+s`
Delete
None

EDITOR-#125 Hotkey save should prevent default.

---

editor-server/src/schema.gql
editor/core/actions/edit.ts
editor/hooks/useEditHandler.tsx

We block the deletion of initial frame (frame index === 0), to prevent bugs
Bug Fix
Resolve https://github.com/NTUEELightDance/LightDance-Editor/issues/124
try to delete the first control frame or posframe

EDITOR-#124 block deletion of initial frames

---

editor/components/ControlBar/FadeSwitch.tsx
editor/components/LightProps/OFcontrols/OFcontrolsContent.tsx
editor/components/LightProps/OFcontrols/index.tsx
editor/components/LightProps/PartMode.tsx
editor/core/actions/currentStatus.ts
editor/core/models/index.d.ts

Improvement
[#135](https://github.com/NTUEELightDance/LightDance-Editor/issues/135)
pull the slider with many parts selected

EDITOR-#136 Mutate current status performance improvement

---

editor/components/ThreeSimulator/ThreeController.ts
editor/components/ThreeSimulator/index.tsx

remove play trigger requestAnimationFrame to Solve performance issue
Bug Fix 
[EDITOR-#137](https://github.com/NTUEELightDance/LightDance-Editor/issues/137)
Play the animation
None

EDITOR-#137 3D performance issue

---

editor/components/ColorPalette/index.tsx
editor/components/ControlBar/FadeSwitch.tsx
editor/components/ControlBar/VolumeSlider.tsx
editor/components/ControlBar/index.tsx
editor/components/DancerTree/index.tsx
editor/components/Header/StateIndicator/index.tsx
editor/components/Header/StateIndicator/styles.module.css
editor/components/Header/index.tsx
editor/components/Loading/index.tsx
editor/components/Settings/index.tsx
editor/components/Wavesurfer/WaveSurferApp.ts
editor/containers/Layout/index.tsx
editor/layouts/beta.json
editor/package.json
editor/yarn.lock

minor ui change and bug fixes, add volume slider
Improvement
Resolve [#135](https://github.com/NTUEELightDance/LightDance-Editor/issues/135)

EDITOR-#135-1 minor ui change and bug fixes

---

editor/components/ThreeSimulator/Controls/SelectControls.ts
editor/components/ThreeSimulator/ThreeComponents/Dancer.ts
editor/components/ThreeSimulator/ThreeController.ts
editor/yarn.lock

1. model should be updated manually
2. composer render should replace renderer render
Bug Fix
[EDITOR-#140](https://github.com/NTUEELightDance/LightDance-Editor/issues/140)
Clicked the play button
None

3D performance and resolution optimization

---

editor/components/ColorPalette/ColorDialog.tsx
editor/components/ColorPalette/ColorListItem.tsx
editor/components/ColorPalette/index.tsx
editor/components/DancerTree/index.tsx
editor/components/Tools/index.tsx

fix the tools drop down covered by select all/ expand all button bug
fix click away behavior in dancer tree is wrong
protect reserved colors
Bug Fix, Improvement 
Resolved [#142](https://github.com/NTUEELightDance/LightDance-Editor/issues/142)

EDITOR-#142 fix ui bugs, protect reserved colors

---

editor/components/ControlBar/FrameControlInput.tsx
editor/components/ControlBar/TimeControlInput.tsx
editor/components/ControlBar/TimeController.tsx
editor/components/ControlBar/VolumeSlider.tsx
editor/components/LightProps/ColorSelector/CustomComponents.tsx
editor/components/LightProps/ColorSelector/index.tsx
editor/components/LightProps/DancerMode.tsx
editor/components/LightProps/OFcontrols/index.tsx
editor/components/LightProps/PropertyPanel/index.tsx

fix some ui bugs, add intuitive time input
Bug Fix, Feature

EDITOR-#145 fix some ui bugs, add intuitive time input

---

editor-server/src/index.ts
editor-server/src/models/EffectList.ts
editor-server/src/models/index.ts
editor-server/src/resolvers/effectList.ts
editor-server/src/resolvers/index.ts
editor-server/src/resolvers/positionFrame.ts
editor-server/src/resolvers/response/effectListResponse.ts
editor-server/src/resolvers/subscriptions/controlMap.ts
editor-server/src/resolvers/subscriptions/controlRecord.ts
editor-server/src/resolvers/subscriptions/effectlist.ts
editor-server/src/resolvers/subscriptions/index.ts
editor-server/src/resolvers/subscriptions/positionMap.ts
editor-server/src/resolvers/subscriptions/positionRecord.ts
editor-server/src/resolvers/subscriptions/topic.ts
editor-server/src/resolvers/types/controlData.ts
editor-server/src/resolvers/types/effectList.ts
editor-server/src/resolvers/types/posData.ts
editor-server/src/schema.gql

Add EffectList
Feature
Resolve [EDITOR-#109. Backend: Add EffectList && EL color](https://github.com/NTUEELightDance/LightDance-Editor/issues/109)
[Link](https://www.notion.so/EffectList-fc4d9efb7ae44684aa33762770a6b475)
* Are there breaking changes for older versions? Yes
* Does this need new documentation? Yes

EDITOR-#109 Add EffectList

---

editor/components/FrameList/index.tsx

See #152.
Bug Fix
None
Fix #152
Delete a frame.
None

EDITOR-#152 FrameList Error Rendering after DEL

---

editor/components/EditorSelector/index.tsx

Fix the bug describe in #154 
Bug Fix
None
Fix #154 
See #154 
None

EDITOR-#154. Switching editor with hotkey 'v' in EDITING mode doesn't alert in some cases.

---

files/data/load.json

update music for 2022
Improvement
Resolve [EDITOR-#156](https://github.com/NTUEELightDance/LightDance-Editor/issues/156)
Play the music
None

EDITOR-#156 update music for 2022

---

editor/components/ControlBar/FrameControlInput.tsx
editor/components/ControlBar/PlayBackController.tsx
editor/components/EditButtons/index.tsx

make playback button change according to the isPlaying state
change edit button loading behavior
Improvement
resolve [#158](https://github.com/NTUEELightDance/LightDance-Editor/issues/158)

EDITOR-#158 minor ui fix

---

editor/components/ThreeSimulator/Controls/OrbitControls.ts

Add support for right click orbitControls
Improvement
Resolve [EDITOR-163](https://github.com/NTUEELightDance/LightDance-Editor/issues/163)
use two finger on trackpad to control the scene viewpoint
None

EDITOR-#163 Add support for right click orbitControls

---

editor/components/ControlBar/ScaleSlider.tsx
editor/components/ControlBar/index.tsx

Add wavesurfer scale slidebar.
Improvement
None
Resolve #165 
Drag the slider.

EDITOR-#165. Add wavesurfer scale slider

---

editor-server/src/resolvers/effectList.ts
editor-server/src/resolvers/index.ts
editor-server/src/resolvers/response/shiftResponse.ts
editor-server/src/resolvers/shift.ts
editor-server/src/resolvers/subscriptions/controlRecord.ts
editor-server/src/resolvers/subscriptions/positionRecord.ts
editor-server/src/resolvers/types/controlData.ts
editor-server/src/resolvers/types/posData.ts
editor-server/src/schema.gql

complete shift
Feature
None
[EDITOR-#168. Backend: Time shifting.](https://github.com/NTUEELightDance/LightDance-Editor/issues/168)
1. start editor-server
2. open http://localhost:4000/api/graphql
3. execute like screenshot below

EDITOR-#168. Backend: Complete shift

---

controller-server/package-lock.json
controller-server/package.json
controller-server/test_websocket/dancerSocket.ts
controller-server/test_websocket/index.d.ts

Enable controller server to communicate with RPi socket.
[Feature]
https://github.com/NTUEELightDance/LightDance-Editor/issues/167
None
* Are there breaking changes for older versions? Yes

EDITOR-#167. Enable controller server RPi socket

---

editor-server/src/models/Color.ts
editor-server/src/resolvers/controlFrame.ts
editor-server/src/resolvers/positionMap.ts
editor-server/src/schema.gql

fix bugs ( positionmap subscription and delete control frame )
[Bug Fix]
Resolve #171 
use graphql playground

EDITOR-#171 DELETE controlFrame bugfix and positionMap subscription bugfix

---

controller-server/test_websocket/controlPanelSocket.ts
controller-server/test_websocket/dancerSocket.ts
controller-server/test_websocket/index.d.ts

Enable control panel client to communicate with control server.
[Feature]
* [play, stop, pause]
Resolve https://github.com/NTUEELightDance/LightDance-Editor/issues/177
None
* Are there breaking changes for older versions? Yes

EDITOR-#177 Controller client socket

---

editor-server/src/index.ts
editor-server/src/middlewares/accessLogger.ts
editor-server/src/models/Logger.ts
editor-server/src/models/index.ts
editor-server/src/mongo.ts
editor-server/src/resolvers/color.ts
editor-server/src/resolvers/control.ts
editor-server/src/resolvers/controlMap.ts
editor-server/src/resolvers/dancer.ts
editor-server/src/resolvers/led.ts
editor-server/src/resolvers/part.ts
editor-server/src/resolvers/position.ts
editor-server/src/resolvers/types/colorMap.ts
editor-server/src/resolvers/types/ledEffectMap.ts
editor-server/src/routes/api/exportLED.ts
editor-server/src/routes/api/exportLogger.ts
editor-server/src/routes/api/uploadLED.ts
editor-server/src/routes/index.ts
editor-server/src/schema.gql
package.json
yarn.lock

1. Add logger
- Only store Mutation access will be store
- Every day, the mongodb will clear the loggers which has been generated for one week automatically
2. delete console.log
3. Modify ledMap
[Bug Fix, Improvement, Feature]
[EDITOR-#189. Backend: Add Logger](https://github.com/NTUEELightDance/LightDance-Editor/issues/189)
1. open graphql
2. do any mutation (you can deliberately send something wrong)
3. open Postman and type thing like screenshots below

EDITOR-#189 Add Logger & Modify ledMap

---

editor-server/src/routes/api/exportLogger.ts
editor-server/src/routes/api/getLogger.ts
editor-server/src/routes/index.ts
editor-server/src/schema.gql

Add id and query for result & error
[Feature]
Resolve [EDITOR-#192. Backend: Add id and query for result & error](https://github.com/NTUEELightDance/LightDance-Editor/issues/192)
[Link](https://www.notion.so/API-Doc-446bdb3ba155471f9c0fb03fe3de5a8e)

EDITOR-#192. Add id and query for result & error

---

controller-server/yarn.lock
editor/app.tsx
editor/components/ThreeSimulator/ThreeComponents/Dancer.ts
editor/core/actions/currentStatus.ts
editor/core/actions/edit.ts
editor/core/actions/timeData.ts
editor/core/utils/color.ts
editor/core/utils/index.ts
editor/core/utils/math.ts

Add support for color fade
Feature
Resolve [EDITOR-#180](https://github.com/NTUEELightDance/LightDance-Editor/issues/180)
Add two frame where a part change different color

EDITOR-#180 Fade Color in THREE Simulator

---

editor/api/index.ts
editor/components/Settings/File/index.tsx
editor/components/Settings/File/utils.tsx
editor/components/Settings/File/validatorShema.tsx

We are not able to download and upload led.json
Feature 
Resolve https://github.com/NTUEELightDance/LightDance-Editor/issues/191
1. make some changes and save them. --> change 1
2. download led.json
3. maker other changes and save. --> change 2
4. upload led.json you just download.
5. refresh
you should see change 1 rather than change 2.

EDITOR-#191 upload and download led.json success

---

editor-server/src/models/LED.ts
editor-server/src/resolvers/controlFrame.ts
editor-server/src/resolvers/controlMap.ts
editor-server/src/resolvers/effectList.ts
editor-server/src/resolvers/inputs/led.ts
editor-server/src/resolvers/positionFrame.ts
editor-server/src/resolvers/positionMap.ts
editor-server/src/resolvers/shift.ts
editor-server/src/resolvers/subscriptions/controlMap.ts
editor-server/src/resolvers/subscriptions/controlRecord.ts
editor-server/src/resolvers/subscriptions/positionMap.ts
editor-server/src/resolvers/subscriptions/positionRecord.ts
editor-server/src/resolvers/types/controlData.ts
editor-server/src/resolvers/types/ledEffect.ts
editor-server/src/resolvers/types/ledEffectMap.ts
editor-server/src/resolvers/types/posData.ts
editor-server/src/routes/api/exportLED.ts
editor-server/src/schema.gql
others/dance_json/test_exportLED.json

RT
Improvement
[EDITOR-#182. Backend: change subscription format](https://github.com/NTUEELightDance/LightDance-Editor/issues/182)

EDITOR-#182. Fix export led & change subscription format

---

editor-server/src/resolvers/positionMap.ts

RT
[Bug Fix]
Resolve [EDITOR-#204. Backend: editPosMap creating new posFrame will error](https://github.com/NTUEELightDance/LightDance-Editor/issues/204)
* Are there breaking changes for older versions? /No

EDITOR-#204. Fix editPosMap creating new frame cause err

---

editor/api/LedAgent.ts
editor/api/index.ts
editor/app.tsx
editor/components/LightProps/DancerMode.tsx
editor/components/LightProps/LEDcontrols/LEDcontrolsContent.tsx
editor/components/LightProps/LEDcontrols/SrcSelector.tsx
editor/components/LightProps/LEDcontrols/index.tsx
editor/components/LightProps/OFcontrols/index.tsx
editor/components/LightProps/PropertyPanel/index.tsx
editor/core/actions/currentStatus.ts
editor/core/actions/timeData.ts
editor/core/models/index.d.ts
editor/core/state/index.ts
editor/core/utils/color.ts
editor/core/utils/index.ts
editor/core/utils/math.ts
editor/graphql/queries.ts
editor/hooks/useDancer.ts
editor/hooks/useLedMap.ts

See #188 
Besides, fix the bug of OFControlContent for not refreshing and the bug for pureStatus not returning from deleteColorCode
Feature
Resolve #188 
1. Add LED Effect from `http://localhost:4000/graphql`
2. Add LED src

EDITOR-#188 Add LED effect support.

---

controller-server/constants/index.ts
controller-server/types/dancer.d.ts
controller-server/types/index.d.ts

* [LightStatusType, ControlType, LedType ] - Task
https://github.com/NTUEELightDance/LightDance-Editor/issues/199
None
None

EDITOR-#199. Control panel websocket message interface

---

editor-server/src/resolvers/controlMap.ts
editor-server/src/resolvers/types/controlData.ts
editor-server/src/resolvers/types/posData.ts

fix bug
[Bug Fix]
[EDITOR-#215. Backend: Control scalar bug + allow src to be empty string](https://github.com/NTUEELightDance/LightDance-Editor/issues/215)

EDITOR-#215. fix bug

---

editor/client/subscription.ts

See #222 
Found that it is caused by using Immer in Apollo cache modify (subscription)
Bug Fix
Resolve #222 
Add, Save
None

EDITOR-#222 Subscription failed in production.

---

controller-server/clientAgent.ts
controller-server/constants/index.ts
controller-server/index.ts
controller-server/test_websocket/controlPanelSocket.ts
controller-server/test_websocket/dancerSocket.ts
controller-server/types/dancer.ts
controller-server/types/index.ts

Add console logs to server and fix responses
Improvement
Resolve #206 
Use websocket client

EDITOR-#206 Fix response and console log

---

editor-server/src/resolvers/color.ts
editor-server/src/resolvers/controlFrame.ts
editor-server/src/resolvers/controlMap.ts
editor-server/src/resolvers/positionFrame.ts
editor-server/src/resolvers/positionMap.ts
editor-server/src/resolvers/types/controlData.ts
editor-server/src/resolvers/types/posData.ts
editor-server/src/schema.gql

Add more error detail
[Improvement]
[EDITOR-#230. Backend: Add more detail to Error message](https://github.com/NTUEELightDance/LightDance-Editor/issues/230)

EDITOR-#230. Add more error detail

---

.gitignore
editor-server/src/resolvers/effectList.ts
editor-server/src/resolvers/types/controlData.ts
editor-server/src/resolvers/types/posData.ts

Fix record subscription bug
[Bug Fix]
Resolve [EDITOR-#226. Backend: ApplyEffectList without clear may return ambiguous subscription](https://github.com/NTUEELightDance/LightDance-Editor/issues/226)
Same as issue

EDITOR-#226. Fix record subscription bug

---

editor-server/src/index.ts

Extend request file size
[Improvement]
Resolve [EDITOR-#234](https://github.com/NTUEELightDance/LightDance-Editor/issues/234)

EDITOR-#234. Extend request file size

---

controller-server/index.ts
controller-server/websocket/controlPanelSocket.ts
controller-server/websocket/dancerSocket.ts

Fix boardInfo type error
Bug Fix
#236 
Use it with rpi client

EDITOR-#236 fix boardInfo type

---

controller-server/index.ts

Fix bugs
Bug Fix 
#236 
Use rpi clients

EDITOR-#236 fix boardInfo bugs

---

editor/core/actions/shiftFrameTime.ts

See #240 
Bug Fix
None
Resolve #240 
Shift with both, position, controller
None

EDITOR-#240. Timeshift both is not functional.

---

controller-server/index.ts
controller-server/types/index.ts
controller-server/websocket/dancerSocket.ts

Finish upload control and LED
Improvement
#236 

EDITOR-#236 fix control type

---

editor-server/src/schema.gql
editor/components/ThreeSimulator/Controls/index.ts
editor/components/ThreeSimulator/index.tsx
editor/core/actions/currentPos.ts
utils/package.json
utils/toGround.js
utils/yarn.lock

Move dancer position to ground with one key
Feature
[EDITOR-#237](https://github.com/NTUEELightDance/LightDance-Editor/issues/237)
Switch to position mode and start editing, press "g" to set all dancer's position to ground.
None

Editor-#237 Move dancer position to ground with one key

---

controller-server/constants/index.ts
controller-server/websocket/dancerSocket.ts

Change upload control to upload of
[Bug Fix]
https://github.com/NTUEELightDance/LightDance-Editor/issues/245
None
None

EDITOR-#245. Change upload control to upload of

---

editor/constants/index.ts
editor/hooks/useWebsocket.ts
editor/types/hooks/webSocket.d.ts

I worked with @FYRichie and verify play, pause, and upload buttons.
The rest buttons are in Todos of this PR.
Feature 
Resolve https://github.com/NTUEELightDance/LightDance-Editor/issues/242
press command center buttons, except those in Todos.

EDITOR-#242 add ts and verify commands

---

editor/components/CommandCenter/CommandCenterTable.tsx
editor/components/CommandCenter/CommandControls.tsx
editor/components/CommandCenter/index.tsx
editor/components/ControlBar/index.tsx
editor/components/Header/LayoutButtons.tsx
editor/components/Header/index.tsx
editor/components/LightProps/OFcontrols/index.tsx
editor/components/Settings/Preference/index.tsx
editor/components/Settings/index.tsx
editor/components/Tools/index.tsx
editor/components/Wavesurfer/index.tsx
editor/containers/Layout/index.tsx
editor/contexts/LayoutContext.tsx
editor/hooks/useWebsocket.ts
editor/layouts/commandCenter.json
editor/types/hooks/webSocket.d.ts

Improvement, Refactoring
Resolve [#233](https://github.com/NTUEELightDance/LightDance-Editor/issues/233)

EDITOR-#233 Refurbish command center UI

---

editor/hooks/useTimeInput.ts

fix time input
Hot Fix 
Resolve [#249](https://github.com/NTUEELightDance/LightDance-Editor/issues/249)

EDITOR-#249 fix time input

---

editor/layouts/editor.json
editor/layouts/mirroredEditor.json

Imporvement
resolve[#253](https://github.com/NTUEELightDance/LightDance-Editor/issues/253)

EDITOR-#253 add back presets, no refactor

---

editor/components/LightProps/PropertyPanel/index.tsx
editor/layouts/editor.json
editor/layouts/mirroredEditor.json

Add a random button for dancer
Feature
Resolve [#255](https://github.com/NTUEELightDance/LightDance-Editor/issues/255)

EDITOR-#255 Add a random button for dancer

---

editor/components/ThreeSimulator/Settings/index.ts
editor/components/ThreeSimulator/ThreeComponents/Dancer.ts
editor/components/ThreeSimulator/ThreeComponents/Part/FiberPart.ts
editor/components/ThreeSimulator/ThreeComponents/Part/LEDPart.ts
editor/components/ThreeSimulator/ThreeController.ts
editor/components/ThreeSimulator/index.tsx
editor/package-lock.json
editor/yarn.lock

preprocess LED  to make it invisible
Bug Fix
Resolve #260
See threeSimulator

EDITOR-#260 Change the visibility of LEDs

---

editor-server/src/resolvers/effectList.ts

Fix querying empty frame bug
[Bug Fix]
[EDITOR-#261. Backend. Query EffectList Bug](https://github.com/NTUEELightDance/LightDance-Editor/issues/261)

EDITOR-#261. Fix querying empty frame bug

---

editor/hooks/useTimeInput.ts

Bug Fix
Resolve [#265](https://github.com/NTUEELightDance/LightDance-Editor/issues/265)

EDITOR-#265 fix timeinput

---

editor/components/LightProps/DancerMode.tsx
editor/components/LightProps/GroupPanel/index.tsx
editor/components/LightProps/LEDcontrols/index.tsx
editor/components/LightProps/OFcontrols/index.tsx
editor/components/LightProps/PartMode.tsx
editor/components/LightProps/PropertyPanel/index.tsx

Feature
Resolve [#267](https://github.com/NTUEELightDance/LightDance-Editor/issues/267)
* Do the license files need updating? Yes
* Are there breaking changes for older versions? Yes
* Does this need new documentation? Yes

EDITOR-#267 add select all button for all panels

---

editor-server/src/models/EffectList.ts
editor-server/src/resolvers/effectList.ts

fix effectlist bug
[Bug Fix ]
[EDITOR-#270. Backend: Effectlist's controlFrames, positionFrames can be Null](https://github.com/NTUEELightDance/LightDance-Editor/issues/270)

EDITOR-#270. fix effectlist bug

---

editor-server/src/resolvers/color.ts
editor-server/src/resolvers/led.ts
editor-server/src/resolvers/response/colorResponse.ts
editor-server/src/schema.gql
editor/components/Settings/File/index.tsx

Fix delete bug
[Bug Fix]
[EDITOR-#272. Backend: Check Color when delete](https://github.com/NTUEELightDance/LightDance-Editor/issues/272)

EDITOR-#272. Fix delete bug

---

utils/config.json
utils/hourglass_led.json
utils/jsonChecker.js
utils/package.json
utils/schemas.js
utils/yarn.lock

Update music once again
Improvement
#251 
Play the music
None

EDITOR #251 Update music once again

---

editor/hooks/useWebsocket.ts

get value directly from reactivestate, without using reactive var
Bug Fix
Resolve #284 

EDITOR-#284 get value directly from reactiveState, without using reactive var

---

editor/components/CommandCenter/CommandControls.tsx
editor/index.css

- add notifications for command center, clear timeout when it should be cleared
- remove toast shadow
Bug Fix
resolve #286 

EDITOR-#286 Notifications  for command center and remove toast shadow

---

editor/api/controlAgent.ts
editor/api/positionAgent.ts
editor/app.tsx
editor/client/subscription.ts
editor/core/actions/edit.ts
editor/core/registerActions/index.ts
editor/graphql/mutations.ts
editor/hooks/useEditHandler.tsx

It's too slow to wait for the response from the backend server.
Improvement
Resolve #293
Edit and Save

EDITOR-#294. Improve the editing performance 

---

controller-server/constants/index.ts
controller-server/websocket/dancerSocket.ts
editor/components/CommandCenter/CommandControls.tsx
editor/constants/index.ts

Add command: Red, Blue, Green
Improvement
#295 
None
None

EDITOR-#295. Command: Red, Blue, Green and currentStatus

---

controller-server/constants/index.ts
controller-server/websocket/dancerSocket.ts
editor/components/CommandCenter/CommandControls.tsx
editor/constants/index.ts

EDITOR-#300. StmInit and darkAll

---

editor-server/src/resolvers/color.ts
editor-server/src/resolvers/led.ts

Fix led, color delete bug
[Bug Fix ]
[EDITOR-#283. Backend: Improvement](https://github.com/NTUEELightDance/LightDance-Editor/issues/283)

EDITOR-#283. fix cannot delete bug

---

editor/components/CommandCenter/CommandControls.tsx
editor/constants/index.ts
editor/hooks/useWebsocket.ts
editor/vite.config.ts
nthu_server/app.py
nthu_server/example.py

Add NTHU STOP for  button to trigger stop by wire
Feature
Resolve #302 
See the command panel
None

EDITOR-#302 Add NTHU STOP for  button to trigger stop by wire

---

README.md
editor/index.tsx

EDITOR-#317 update readme

---

.gitignore
editor-server/README.md
editor-server/prisma/schema.prisma
editor-server/src/resolvers/color.ts
editor-server/src/schema.gql

Define Prisma Schema 
Add Color resolver editColorCodeByColor precheck
Bug Fix + Feature
resolve #331 
npx prisma migrate dev --name init

EDITOR-#331. Define Prisma Schema & Add Color resolver editColorCodeByColor precheck

---

controller-server/pnpm-lock.yaml
editor/api/authAgent.ts
editor/api/positionAgent.ts
editor/core/actions/currentStatus.ts
editor/core/actions/edit.ts
editor/core/actions/selected.ts
editor/core/actions/shiftFrameTime.ts
editor/core/state/index.ts
editor/core/utils/genJson.ts
editor/core/utils/led.ts
editor/core/utils/localStorage.ts
editor/hooks/useColorMap.ts
editor/hooks/useEditHandler.tsx
editor/hooks/usePartGroups.ts
editor/hooks/useWebsocket.ts

fix warning of eslint in this file
Improvement 
resolve #342 
I haven't tested it before because I can't find anything different.

Editor #342 fix warning of eslint in editor

---

editor-server/prisma/schema.prisma
editor-server/src/resolvers/index.ts
editor-server/src/routes/api/exportData.ts
editor-server/src/routes/api/uploadData.ts
editor-server/src/schema.gql

Add EditLEDEffect
Feature
resolve #364 

EDITOR-#364. Add EditLEDEffect

---

editor-server/src/resolvers/types/ledEffectMap.ts

fix backend LED resolver
Bug Fix
#371 
graphql server at localhost:4000/graphql

EDITOR-#371 Fix LED

---

controller-server/README.md
controller-server/package.json
controller-server/types/index.ts
controller-server/websocket/controlPanelSocket.ts
controller-server/websocket/dancerSocket.ts
controller-server/websocket/testControlPanel1.js
controller-server/websocket/testRPi1.js

Type needs to be changed according to the new protocols in the controller-server
New Protocols: https://www.notion.so/New-Protocols-447faa3fe5494722bd2e8c2e73c38848
Improvement 
Controller-Server: Change types according to New Protocols #341
-->](https://github.com/NTUEELightDance/LightDance-Editor/issues/341)
To test controller-server, run
```
yarn dev:controller-server
```
under the Lightdance-Editor folder
To setup a test RPi Client, run **under the controller-server folder**
```
yarn test-rpi
```
To setup a test Contrtol Panel Client, run **under the controller-server folder**
```
yarn test-control
```

Editor #341: Controller-Server: Change types according to New Protocols

---

editor-server/prisma/schema.prisma
editor-server/src/index.ts
editor-server/src/resolvers/controlFrame.ts
editor-server/src/resolvers/effectList.ts
editor-server/src/resolvers/inputs/controlFrame.ts
editor-server/src/resolvers/inputs/dancer.ts
editor-server/src/resolvers/inputs/led.ts
editor-server/src/resolvers/inputs/part.ts
editor-server/src/resolvers/inputs/positionFrame.ts
editor-server/src/resolvers/led.ts
editor-server/src/resolvers/positionFrame.ts
editor-server/src/resolvers/requestEdit.ts
editor-server/src/resolvers/response/ledEffectResponse.ts
editor-server/src/resolvers/response/requestEditResponse.ts
editor-server/src/resolvers/shift.ts
editor-server/src/resolvers/subscriptions/color.ts
editor-server/src/resolvers/subscriptions/controlMap.ts
editor-server/src/resolvers/subscriptions/controlRecord.ts
editor-server/src/resolvers/subscriptions/dancer.ts
editor-server/src/resolvers/subscriptions/effectlist.ts
editor-server/src/resolvers/subscriptions/positionMap.ts
editor-server/src/resolvers/subscriptions/positionRecord.ts
editor-server/src/schema.gql

1. add editingLEDEffect model and related resolvers
2. change type declaration of several variables(ex: id, start, end(from Float to Int))
Feature
#378 
graphql playground at localhost:4000/graphql

EDITOR-#378 Add editingLEDEffect & More Precise Type Declaration

---

editor-server/src/resolvers/controlFrame.ts
editor-server/src/resolvers/led.ts
editor-server/src/resolvers/subscriptions/index.ts
editor-server/src/resolvers/subscriptions/led.ts
editor-server/src/resolvers/subscriptions/topic.ts
editor-server/src/schema.gql

add resolver for LED update
add subscription to LED resolver
feature
EDITOR-#377 LED Subscription

EDITOR#377. Add LED update and subscription 

---

editor-server/src/resolvers/controlFrame.ts
editor-server/src/resolvers/positionFrame.ts
editor-server/src/routes/api/uploadData.ts
editor-server/src/schema.gql

Add new mutations that are able to initialize data in single frame.
Feature
#382 
`pnpm dev:editor`
Go to `localhost:4000/graphql` and test them.

EDITOR-#382. Add addControlFrameData & addPositionFrameData mutations

---

editor-server/prisma/schema.prisma
editor-server/src/resolvers/inputs/part.ts
editor-server/src/resolvers/part.ts
editor-server/src/routes/api/exportData.ts
editor-server/src/routes/api/uploadData.ts
editor-server/src/schema.gql
editor-server/src/types/global.ts
utils/jsons/exportDataEmpty.json

EDITOR-#389. Add length to LED part

---

editor-server/src/resolvers/led.ts
editor-server/src/resolvers/response/ledEffectResponse.ts
editor-server/src/schema.gql

Fix the bugs of return types in resolver/led.ts
Bug Fix
no

Editor-#384 Backend: fix addLED return value and fix editLED return effects[0].effect is null

---

editor/components/Clipboard/index.tsx
editor/components/LightProps/PartMode.tsx
editor/components/ThreeSimulator/Settings/index.ts
editor/components/ThreeSimulator/ThreeComponents/Part/LEDPart.ts
editor/components/ThreeSimulator/ThreeComponents/Part/Part.ts
editor/components/Wavesurfer/WaveSurferApp.ts
editor/core/actions/currentStatus.ts
editor/core/actions/initialize.ts
editor/core/actions/led.ts
editor/core/models/index.ts
editor/pages/App.tsx

fix editor bugs
Bug Fix
resolve #394 

EDITOR #394 fix editor bugs

---

editor-server/prisma/schema.prisma
editor-server/src/middlewares/accessLogger.ts
editor-server/src/routes/api/exportLogger.ts

Add logger back
export logger
Feature
resolve #397 

EDITOR-#397 Backend Add logger back

---

editor-server/src/resolvers/color.ts
editor-server/src/resolvers/inputs/led.ts
editor-server/src/resolvers/led.ts
editor-server/src/schema.gql
editor-server/src/types/global.ts

1. adjust editLED to accept updating LED name
2. check if LED is used in ControlData when renaming LED
3. check if color is used in ControlData when renaming color
Feature
#401 
graphql playground at localhost:4000/graphql

EDITOR-#401 Backend: Enable rename of color & ledEffect

---

editor/components/ThreeSimulator/Controls/SelectControls.ts
editor/core/actions/selected.ts

DEBUG position mode fail
Bug Fix
[EDITOR-#406](https://github.com/NTUEELightDance/LightDance-Editor/issues/406)

EDITOR-#406 debug position mode fail

---

editor/components/Header/EditorSelector/index.tsx
editor/components/LEDEffectList/LEDEffectDialog.tsx
editor/components/LEDEffectList/LEDPartButton.tsx
editor/components/LEDEffectList/ModelButton.tsx
editor/components/LEDEffectList/index.tsx
editor/containers/Layout/index.tsx
editor/layouts/defaultEditor.json
files/data/load.json

Entrance and setup for LED Editor
Feature
#402 

Editor #402 Entrance and setup for LED Editor

---

editor/components/LightProps/ColorSelector/index.tsx
editor/components/LightProps/IntensityControl.tsx
editor/components/LightProps/LEDcontrols/LEDcontrolsContent.tsx
editor/components/LightProps/LEDcontrols/SrcSelector.tsx
editor/components/LightProps/OFcontrols/OFcontrolsContent.tsx
editor/components/LightProps/PartMode.tsx
editor/components/LightProps/PropertyPanel/index.tsx

UI/UX improvements
Feature
resolve #417 

EDITOR-#417 UI/UX improvements

---

controller-server/README.md
controller-server/constants/index.ts
controller-server/constants/macList.ts
controller-server/database/dancerControlJson.ts
controller-server/database/dancerLED.ts
controller-server/database/dancerOF.ts
controller-server/index.ts
controller-server/types/index.ts
controller-server/websocket/controlPanelSocket.ts
controller-server/websocket/dancerSocket.ts
controller-server/websocket/testControlPanel1.js

RPi changed sending data type to 
``` javascript
{
"command": "boardInfo",
"status": 0,
"payload": 
{
"type":  "RPi",
"info": {
"macaddr" : macaddr,
}
}
}
```
and request server to send back payload with [control.json, Of.json, LED.json]
Improvement
* Testing with ws_client_test.py provided by RPi group:
* On RPi client connection
* After control panel set all the upload commands
Quite long, but one might be able to see that payload is of type [control.json, Of.json, LED.json]

Editor #421 Controller server: Save MAC Address in Controller Server & Renew Communication Protocols with RPi

---

editor-server/prisma/schema.prisma
editor-server/src/routes/api/getDancerFiberData.ts
editor-server/src/routes/api/getDancerLEDData.ts
editor-server/src/routes/index.ts
editor-server/src/schema.gql

add control-server required api
Feature
resolve #426

EDITOR-#426 add control-server required api

---

editor-server/src/routes/api/getDancerLEDData.ts

EDITOR-#429 Modify led data

---

controller-server/api/index.ts
controller-server/types/RPiMessage.ts
controller-server/types/controlPanelMessage.ts
controller-server/websocket/RPi/handlers.ts
controller-server/websocket/controlPanel/handler.ts
controller-server/websocket/controlPanel/index.ts
editor/components/CommandCenter/CommandControls.tsx
editor/hooks/useCommandCenter.ts

add close hardware interface in controller server
Feature

EDITOR#438 add close hardware interface in controller server

---

editor-server/src/routes/api/getDancerLEDData.ts

EDITOR-#445 Fix LED Effect

---

editor-server/src/routes/api/check_token.rs
editor-server/src/routes/api/mod.rs

Add the CheckToken API and update the mod.rs file to include the route
Feature
None
#456 
Check the checktoken response on the browser

EDITOR-#456 add CheckToken and update mod.rs

---

controller-server/websocket/RPi/handlers.ts
editor-server/prisma/schema.prisma
editor-server/src/routes/api/get_dancer_led_data.rs
editor-server/src/routes/api/mod.rs

pull request
feature
None (bug maybe)
#451 
with editor or postman
None

Editor #451 Rewrite GetDancerLEDData

---

controller-server/pnpm-lock.yaml
editor-server/pnpm-lock.yaml
editor/components/ControlBar/PlayBackController.tsx
editor/components/ControlBar/RateControlInput.tsx
editor/components/Wavesurfer/WaveSurferApp.ts
editor/pnpm-lock.yaml
file-server/pnpm-lock.yaml
pnpm-lock.yaml
utils/pnpm-lock.yaml

control playback rate, range (0, 8]
[Feature]
None
#472 
edit textField beside play/pause icon

EDITOR-#472 Control playback rate

---

controller-server/websocket/RPi/handlers.ts
editor-server/src/routes/api/get_dancer_led_data.rs

replace unwrap with into_result in get_dancer_led_data.rs.
Bug Fix
None
#466 
postman or editor

Editor #466 add error handling for sql queries

---

controller-server/websocket/RPi/handlers.ts
editor-server/src/routes/api/get_dancer_led_data.rs

Reverts NTUEELightDance/LightDance-Editor#468

Revert "Editor #466 add error handling for sql queries"

---

controller-server/websocket/RPi/handlers.ts
editor-server/src/routes/api/get_dancer_led_data.rs

add error handling to get_dancer_led_data.rs.

Editor #466 Add error handling

---

editor-server/src/routes/api/get_dancer_fiber_data.rs
editor-server/src/routes/api/mod.rs

pull request
Feature
None
#461 
postman, editor
None 
Maybe the color map should be moved to a global variable where it can be used by both get_dancer_fiber_data.rs and get_dancer_led_data.rs.

Editor #461 Rewrite GetDancerFiberData

---

editor/components/LightProps/IntensityControl.tsx

intensity start from 1
[Feature]
#476

Editor #476 Intensity start from 1

---

editor-server/Cargo.lock
editor-server/prisma/Cargo.toml
editor-server/prisma/schema.prisma
editor-server/src/db/types/dancer.rs
editor-server/src/db/types/editing_control_frame.rs
editor-server/src/db/types/editing_led_effect.rs
editor-server/src/db/types/editing_position_frame.rs
editor-server/src/db/types/led_effect.rs
editor-server/src/db/types/mod.rs
editor-server/src/db/types/position.rs
editor-server/src/db/types/position_frame.rs
editor-server/src/graphql/mutations/mod.rs
editor-server/src/graphql/mutations/position_frame.rs
editor-server/src/graphql/mutations/position_map.rs
editor-server/src/graphql/mutations/request_edit.rs
editor-server/src/graphql/queries/mod.rs
editor-server/src/graphql/queries/position_frame.rs
editor-server/src/graphql/queries/position_map.rs
editor-server/src/graphql/subscriptions/mod.rs
editor-server/src/graphql/subscriptions/position_map.rs
editor-server/src/graphql/subscriptions/position_record.rs
editor-server/src/graphql/types/map.rs
editor-server/src/graphql/types/mod.rs
editor-server/src/graphql/types/pos_data.rs

Complete all PositionMap's, PositionFrame's, RequestEdit resolvers and some data types.
[Feature]
None
close #467 
graphql playground

EDITOR-#467 PositionMap, PositionFrame, RequestEdit resolvers

---

dev.docker-compose.yml
editor-server/src/db/types/dancer.rs
editor-server/src/db/types/part.rs
editor-server/src/graphql/mutations/color.rs
editor-server/src/graphql/mutations/dancer.rs
editor-server/src/graphql/mutations/mod.rs
editor-server/src/graphql/subscriptions/dancer.rs
editor-server/src/graphql/subscriptions/mod.rs
editor-server/src/graphql/types/dancer.rs
editor-server/src/graphql/types/mod.rs
editor-server/src/routes/api/get_dancer_fiber_data.rs

rewrite dancer in rust
done TODOs in color
resolve #485 and #496 

EDITOR-#485 Rewrite dancer and color for graphql

---

editor/components/LightProps/IntensityControl.tsx
editor/components/LightProps/LEDcontrols/SrcSelector.tsx
editor/components/LightProps/OFcontrols/ColorSelector/index.tsx

有更改 control, pos, effect 的時候要自動進入 edit mode
[ Feature]
#504

EDITOR-#504 auto switch edit mode

---

editor-server/src/graphql/mutations/mod.rs
editor-server/src/graphql/mutations/shift.rs
editor-server/src/graphql/subscriptions/control_record.rs
editor-server/src/graphql/subscriptions/position_record.rs
editor-server/src/graphql/types/pos_data.rs

rewrite backend code in rust
Feature
None
#463 

Editor #463 Rewrite Shift Resolver

---

editor-blender/graphqls/mutations.py

Editor #521

---

editor-server/src/routes/api/get_dancer_led_data.rs

debug: return headers instead of HeaderMap::new()
[Bug Fix]
close #525 
postman

EDITOR-#525 [SERVER] fix: incorrect response in `get_dancer_led_data.rs`

---

editor-blender/api/led_agent.py
editor-blender/client/subscription.py
editor-blender/core/actions/property/led_editor.py
editor-blender/core/actions/state/control_editor.py
editor-blender/core/actions/state/led_editor.py
editor-blender/core/actions/state/led_map.py
editor-blender/core/models/__init__.py
editor-blender/core/states/__init__.py
editor-blender/core/utils/convert.py
editor-blender/graphqls/mutations.py
editor-blender/graphqls/subscriptions.py
editor-blender/operators/editor/__init__.py
editor-blender/panels/led_editor/__init__.py
editor-blender/properties/ui/led_editor.py
editor-blender/properties/ui/types.py
editor-server/src/graphql/mutations/led.rs
editor-server/src/graphql/subscriptions/led.rs

EDITOR-#529 [BLENDER] LED effect editor

---

editor-blender/handlers/__init__.py
editor-blender/handlers/keymap.py
editor-blender/handlers/name_tag.py
editor-blender/operators/clipboard/__init__.py

Used blf and the result looks like this:

EDITOR-#535 [BLENDER] Dancer name tag

---

editor-server/src/routes/api/get_dancer_fiber_data.rs
editor-server/src/routes/api/get_dancer_led_data.rs

**###** What is this PR for?
bug fix
Bug Fix
#542 
postman

EDITOR-#542 bug fix in get_dancer_led_data

---

editor-blender/core/actions/property/animation_data/control.py
editor-blender/core/actions/property/animation_data/position.py
editor-blender/core/actions/property/revision.py

EDITOR-#554. Fix duplicated deletes

---

editor-blender/operators/select/__init__.py

[BLENDER] EDITOR-#557 Add custom select all / select random operator

---

editor-blender/handlers/keymap.py
editor-blender/operators/__init__.py
editor-blender/operators/select/__init__.py

EDITOR-#557 Add selection shortcut

---

editor-blender/operators/select/__init__.py

Fix custom select all / select random operator

---

controller-server/configs/pinMapTable.ts

[CONTROLLER] update pinMapTable shoe led

---

utils/merge.js

EDITOR-#556 fix effect structure in merge.js

---

editor-server/prisma/schema.prisma
editor-server/src/db/types/position.rs
editor-server/src/graphql/mutations/position_frame.rs
editor-server/src/graphql/mutations/position_map.rs
editor-server/src/routes/api/export_data.rs
editor-server/src/routes/api/upload_data.rs
editor-server/src/types/global.rs
editor-server/src/utils/data.rs

add rx, ry, rz to PositionData
[Improvement]
No
close #573 
Graphql & Postman

EDITOR-#170 [SERVER] add rx, ry, rz to PositionData

---

editor-blender/api/control_agent.py
editor-blender/core/actions/property/lights.py
editor-blender/core/actions/state/control_editor.py
editor-blender/core/actions/state/current_status.py
editor-blender/core/models/__init__.py
editor-blender/core/states/__init__.py
editor-blender/core/utils/convert.py
editor-blender/graphqls/mutations.py
editor-blender/graphqls/queries.py
editor-blender/graphqls/subscriptions.py
editor-blender/handlers/objects.py
editor-blender/operators/editor/__init__.py
editor-blender/panels/control_editor/__init__.py
editor-blender/properties/lights.py
editor-blender/properties/ui/control_editor.py
editor-server/src/graphql/mutations/control_frame.rs
editor-server/src/graphql/mutations/control_map.rs

[BLENDER] #572 Control editor LED bulb support (WIP)

---

controller-server/configs/pinMapTable.ts

Reverts NTUEELightDance/LightDance-Editor#589

Revert "update pinMapTable"

---

controller-server/configs/dancerTable.ts
controller-server/websocket/controlPanel/handler.ts

2024 dancer table last update, modify music offset

---

.gitignore
editor-server/Cargo.lock
editor-server/Cargo.toml
editor-server/prisma/src/main.rs
editor-server/src/db/clients.rs
editor-server/src/main.rs
editor-server/src/routes/api/mod.rs
editor-server/src/tracing/mod.rs

Add API tracing

---

editor-server/prisma/schema.prisma
editor-server/src/db/types/position.rs
editor-server/src/graphql/mutations/position_frame.rs
editor-server/src/graphql/mutations/position_map.rs
editor-server/src/routes/api/export_data.rs
editor-server/src/routes/api/upload_data.rs
editor-server/src/types/global.rs
editor-server/src/utils/data.rs

Rotation backend modified, waiting for testing.

EDITOR-#609 support rotation--wait for testing

---

editor-server/Cargo.lock
editor-server/Cargo.toml
editor-server/src/graphql/subscriptor/websocket.rs
editor-server/src/main.rs
editor-server/src/routes/api/check_token.rs
editor-server/src/routes/api/create_user.rs
editor-server/src/routes/api/export_data.rs
editor-server/src/routes/api/get_dancer_fiber_data.rs
editor-server/src/routes/api/get_dancer_led_data.rs
editor-server/src/routes/api/login.rs
editor-server/src/routes/api/logout.rs
editor-server/src/routes/graphql.rs
editor-server/src/server/extractors/authentication.rs
editor-server/src/tracing/mod.rs

給別人看code
Improvement
因axum更新導致的剩餘錯誤需要排查

update axum to 0.8.1 and fix some error(have not finished, do not merge)

---

editor-server/tests/position_frame.rs

Editor #617
